# Generated by Django 6.1 on 2026-09-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
